export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART';
export const DESCREAS_QUANTITY = 'DESCREAS_QUANTITY';
export const INCREAS_QUANTITY = 'INCREAS_QUANTITY';